sudo: required
services:
  - docker

before_install:
  - docker build -t shogotagami/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true shogotagami/react-test npm test

after_success:
  - docker build -t shogotagami/multi-client ./client
  - docker build -t shogotagami/multi-nginx ./nginx
  - docker build -t shogotagami/multi-server ./server
  - docker build -t shogotagami/multi-worker ./worker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push shogotagami/multi-client
  - docker push shogotagami/multi-nginx
  - docker push shogotagami/multi-server
  - docker push shogotagami/multi-worker

deploy:
  edge: true
  provider: elasticbeanstalk
  region: us-east-2
  app: fib-counter
  env: FibCounter-env
  bucket_name: elasticbeanstalk-us-east-2-927395323393
  bucket_path: fib-counter
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWS_SECRET_KEY
